name: ChatColor
author: BreadMan
main: com.breadman.chatcolor.ChatColorPlugin
version: 1.0.0
api-version: 1.13
commands:
chatcolor:
description: Set your chat color.
usage: /chatcolor <color|list|reset>
permission: chatcolor.command
permissions:
chatcolor.command:
default: true
chatcolor.use:
default: true
chatcolor.color.*:
default: op
chatcolor.bypass:
default: op
